# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true
    image: ubuntu-1604:201903-01

    working_directory: ~/scalardl-web-client-sdk

    steps:
      - checkout
      # Restore dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run: #STABLE
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run:
          name: Docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: Spin container via docker compose
          command: docker-compose up -d
          working_directory: .circleci/

      - run:
          name: Debug docker ps
          command: docker ps && sudo netstat

      - run:
          name: Copy cqlsh
          command: docker cp ./create_schema.cql cassandra:/create_schema.cql
          working_directory: .circleci/

      - run:
          name: List all listening port
          command: netstat -lntp && pwd && ls -a ../

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install node@10.15.3
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v10.15.3
            nvm alias default v10.15.3
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

      - run:
          name: Execute cqlsh
          command: docker exec cassandra cqlsh -f /create_schema.cql

      - run:
          name: Docker logs scalar dl
          command: docker logs scalar-ledger

      - run:
          name: Docker logs envoy
          command: docker logs envoy

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      # run tests
      - run:
          command: npm test
          environment:
            MOCHA_FILE: "~/scalardl-web-client-sdk/mochawesome-report/mochawesome.html"
          when: always

      - store_test_results:
          path: ~/scalardl-web-client-sdk/mochawesome-report

      - store_artifacts:
          path: ~/scalardl-web-client-sdk/mochawesome-report
